import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ============ 种子标签 ============
const LABELS = [
  "免住宅费", "免偏远费", "超重费用有打折", "免超长费",
  "材积除6000", "免关税预付手续费", "免更改地址费",
  "体积除5800", "材积除7000",
];

// ============ 渠道种子数据（来源：by56 真实接口样本） ============
const CHANNELS = [
  {
    channelKey: "5861ac7a-3f77-4722-ac8d-f6326a45c359",
    channelName: "H-59 HKDHL代理价(美洲）",
    channelCode: "BSA00002-H-59 HKDHL-US",
    supplierName: "中技物流",
    modeCode: "DHL-HK",
    channelTypeCode: 1,
    currency: 1,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 5,
    cargoTypeInfo: "普货,内置电池,配套电池,手机(无电),手机(内电),手机(配电),纺织品,木箱",
    volumnBase: 5000,
    isTax: false,
    channelDescription: "截单时间14：00，当天过港",
    riskWarning: "途径美国纽约机场(JFK)入口，被当地海关确认是[虚假描述]的货会产生高额罚款",
    batteryNotice: "可接内置锂离子电池货；可接配套锂离子电池货；不接移动电源",
    pricePerKg: 71.93,
    wareFlightDesc: "交仓后次日或第三天提取上网",
    flightDesc: "美洲排航班1-2天左右",
    wareShortCode: "SZX1",
    fees: [{ feeName: "排仓费", feeUnit: 2, price: 30.00, isAddFreight: true }],
    labelNames: ["免住宅费", "免偏远费", "材积除6000", "免关税预付手续费", "免更改地址费", "体积除5800", "材积除7000"],
  },
  {
    channelKey: "e1f83f0a-bad7-4554-b92f-93fe592f2ff9",
    channelName: "H-70 HKDHL美国小货",
    channelCode: "H-70 D-01",
    supplierName: "中技物流",
    modeCode: "DHL-HK",
    channelTypeCode: 6,
    currency: 3,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 6,
    cargoTypeInfo: "普货,内置电池,配套电池,纺织品,木箱",
    volumnBase: 5000,
    channelDescription: "次日提取；0.5-30KG有服务，可接关税预付",
    riskWarning: "带电池及配套电池没有备注的情况下，每票罚款最低200元",
    batteryNotice: "带电须如实申报！",
    pricePerKg: 79.25,
    wareFlightDesc: "当天或次日提取",
    flightDesc: "提取后1-2天飞",
    wareShortCode: "SZX1",
    fees: [],
    labelNames: ["免住宅费", "免偏远费", "超重费用有打折", "免超长费", "材积除6000"],
  },
  {
    channelKey: "dac46873-db10-4131-895e-cb4671b641ce",
    channelName: "EUB19 大陆UPS_红单6",
    channelCode: "EUB19 大陆UPS_红单6000",
    supplierName: "深圳市迅捷国际货运代理有限公司",
    modeCode: "UPS-CN",
    channelTypeCode: 6,
    currency: 1,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 10,
    cargoTypeInfo: "普货,内置电池,配套电池,纺织品,木箱",
    volumnBase: 5000,
    serviceType: "红单速快",
    channelDescription: "目前当天或次日提取上网；一票多件，每件最低计费重5KG",
    batteryNotice: "带电 需提供正确的有效期内的航空鉴定报告",
    pricePerKg: 83.22,
    wareFlightDesc: "1-2天提取",
    flightDesc: "美洲排航班5-8天",
    wareShortCode: "SZX255",
    fees: [
      { feeName: "预录费", feeUnit: 1, price: 20.00, isAddFreight: true },
      { feeName: "排仓费", feeUnit: 2, price: 22.13, isAddFreight: true },
      { feeName: "国际加工费", feeUnit: 1, price: 18.40, isAddFreight: true },
    ],
    labelNames: ["材积除6000"],
  },
  {
    channelKey: "a0d8d5c6-545d-41f3-933d-48ee8835e54f",
    channelName: "H-51 香港联邦FICP",
    channelCode: "H-51 VIP-HKFedex-FICP-U价",
    supplierName: "中技物流",
    modeCode: "FEDEX-HK",
    channelTypeCode: 6,
    currency: 3,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 7,
    cargoTypeInfo: "普货,内置电池,配套电池,电容,纺织品,木箱",
    volumnBase: 5000,
    serviceType: "FICP",
    channelDescription: "0.5-32.5KG小货段按查价重量为准即可，大货实重35KG起收",
    batteryNotice: "带电需如实申报",
    pricePerKg: 83.33,
    wareFlightDesc: "次日提取",
    flightDesc: "提取后1-2天起飞",
    wareShortCode: "SZX1",
    fees: [{ feeName: "美国属地进口处理费", feeUnit: 1, price: 6.83, isAddFreight: false }],
    labelNames: ["免偏远费"],
  },
  {
    channelKey: "db02c9f8-8055-4679-b703-f8ff38f23b6d",
    channelName: "H-18 FB-IE 经济价",
    channelCode: "BSA00002-H-18 FB-IE",
    supplierName: "中技物流",
    modeCode: "FEDEX-HK",
    channelTypeCode: 1,
    currency: 3,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 7,
    cargoTypeInfo: "普货,内置电池,配套电池,手机(无电),手机(内电),手机(配电),电容,纺织品,木箱",
    volumnBase: 5000,
    serviceType: "经济服务",
    channelDescription: "下午3点截单",
    batteryNotice: "印度尼西亚等带锂电池类的货物需提供MSDS、UN38.3等",
    pricePerKg: 83.62,
    wareFlightDesc: "当天或者次日提取",
    flightDesc: "欧洲美洲在香港排航班2-3天",
    wareShortCode: "SZX1",
    fees: [
      { feeName: "指定原发票", feeUnit: 1, price: 0.01, isAddFreight: true },
      { feeName: "美国属地进口处理费", feeUnit: 1, price: 18.03, isAddFreight: false },
    ],
    labelNames: ["免关税预付手续费"],
  },
  {
    channelKey: "5a72160d-4cdf-406b-bc08-7331fb63aaf4",
    channelName: "EUA35 深圳UPS蓝单小货6-A价",
    channelCode: "CNUPS-02/6000",
    supplierName: "深圳市众鑫邦国际货运代理有限公司",
    modeCode: "UPS-CN",
    channelTypeCode: 6,
    currency: 1,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 10,
    cargoTypeInfo: "普货,木箱",
    volumnBase: 5000,
    serviceType: "蓝单快捷",
    channelDescription: "法国需要提供税号；只要是一票多件 单件重量不足4KG按4KG起收费",
    pricePerKg: 83.69,
    wareFlightDesc: "美洲限量排仓1-2天",
    flightDesc: "美洲排航班5-7天",
    wareShortCode: "SZX197",
    fees: [{ feeName: "国际加工费", feeUnit: 1, price: 18.40, isAddFreight: false }],
    labelNames: ["免住宅费"],
  },
  {
    channelKey: "67f58e1b-1e85-419f-9c9e-511926fa38b7",
    channelName: "EUA09 HKUPS红单小货价",
    channelCode: "BSA00002-EUA09 HKUPS红单小货价",
    supplierName: "深圳市锦洋达国际货运代理有限公司",
    modeCode: "UPS-HK",
    channelTypeCode: 6,
    currency: 1,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 12,
    cargoTypeInfo: "普货,内置电池,配套电池,手机(无电),手机(内电),手机(配电),纺织品,木箱",
    volumnBase: 5000,
    serviceType: "红单速快",
    channelDescription: "一票多件货物，单件平均计费重要达到6KG/件",
    batteryNotice: "带电请如实申报！",
    pricePerKg: 84.62,
    wareFlightDesc: "美洲排仓3-5天",
    flightDesc: "欧美在香港排航班3-5天",
    wareShortCode: "SZX254",
    fees: [{ feeName: "国际加工费", feeUnit: 1, price: 19.00, isAddFreight: true }],
    labelNames: [],
  },
  {
    channelKey: "cb33a8dc-4733-4ea0-b46c-0de058bb6660",
    channelName: "H-107 香港联邦FICP",
    channelCode: "H-107 FICPDRC",
    supplierName: "中技物流",
    modeCode: "FEDEX-HK",
    channelTypeCode: 6,
    currency: 3,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 7,
    cargoTypeInfo: "普货,内置电池,配套电池,电容,纺织品,木箱",
    volumnBase: 5000,
    serviceType: "FICP",
    channelDescription: "下午3点截单",
    batteryNotice: "带电需如实申报",
    pricePerKg: 85.10,
    wareFlightDesc: "次日提取",
    flightDesc: "提取后1-2天起飞",
    wareShortCode: "SZX1",
    fees: [{ feeName: "美国属地进口处理费", feeUnit: 1, price: 6.83, isAddFreight: false }],
    labelNames: ["免住宅费", "免偏远费", "免关税预付手续费"],
  },
  {
    channelKey: "367e1cdd-6d01-4657-8842-085eff8c1bdc",
    channelName: "H-18 FB-IP 优先价",
    channelCode: "BSA00002-H-18 FB-IP",
    supplierName: "中技物流",
    modeCode: "FEDEX-HK",
    channelTypeCode: 1,
    currency: 3,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 7,
    cargoTypeInfo: "普货,内置电池,配套电池,手机(无电),手机(内电),手机(配电),电容,纺织品,木箱",
    volumnBase: 5000,
    channelDescription: "下午3点截单",
    batteryNotice: "电池货必须如实、准确申报",
    pricePerKg: 90.18,
    wareFlightDesc: "当天或次日提取",
    flightDesc: "提取后1-2天起飞",
    wareShortCode: "SZX1",
    fees: [
      { feeName: "指定原发票", feeUnit: 1, price: 0.01, isAddFreight: true },
      { feeName: "美国属地进口处理费", feeUnit: 1, price: 18.03, isAddFreight: false },
    ],
    labelNames: ["免关税预付手续费"],
  },
  {
    channelKey: "b8442103-f3f9-4dc3-8721-73dadd2a5625",
    channelName: "EUA35 深圳UPS特快5",
    channelCode: "EUA35 CNUPS-03",
    supplierName: "深圳市众鑫邦国际货运代理有限公司",
    modeCode: "UPS-CN",
    channelTypeCode: 6,
    currency: 1,
    startCityName: "深圳市",
    countryCode: "US",
    countryName: "美国",
    workDays: 3,
    cargoTypeInfo: "普货,内置电池,配套电池",
    volumnBase: 5000,
    serviceType: "UPS特快",
    channelDescription: "法国需要提供税号；此渠道需提前给收件地址测试",
    batteryNotice: "必须有合格的航空运输鉴定报告书",
    pricePerKg: 91.00,
    wareFlightDesc: "美洲限量排仓1-2天",
    flightDesc: "",
    wareShortCode: "SZX197",
    fees: [{ feeName: "国际加工费", feeUnit: 1, price: 18.40, isAddFreight: false }],
    labelNames: ["免住宅费"],
  },
];

async function main() {
  // 1. 种子客户
  const c = await prisma.customer.upsert({
    where: { id: "demo-customer" },
    update: {},
    create: {
      id: "demo-customer",
      name: "深圳市示例科技有限公司",
      contact: "李经理",
      phone: "13800000000",
      email: "demo@example.com",
      creditLimit: 50000,
      remark: "种子数据",
    },
  });
  console.log("✓ Customer:", c.name);

  // 2. 种子标签
  const labelMap = new Map<string, number>();
  for (const name of LABELS) {
    const l = await prisma.channelLabel.upsert({
      where: { labelName: name },
      update: {},
      create: { labelName: name, isPublic: true },
    });
    labelMap.set(name, l.id);
  }
  console.log(`✓ Labels: ${labelMap.size} 条`);

  // 3. 种子渠道
  let channelCount = 0;
  for (const ch of CHANNELS) {
    const { fees, labelNames, ...channelData } = ch;

    // 删旧 → 创新（幂等）
    await prisma.channel.deleteMany({ where: { channelKey: channelData.channelKey } });

    await prisma.channel.create({
      data: {
        ...channelData,
        pricePerKg: channelData.pricePerKg,
        minWeight: 0.5,
        isActive: true,
        fees: {
          create: fees.map((f) => ({
            feeName: f.feeName,
            feeUnit: f.feeUnit,
            price: f.price,
            isAddFreight: f.isAddFreight,
          })),
        },
        labels: {
          create: labelNames
            .filter((n) => labelMap.has(n))
            .map((n) => ({ labelId: labelMap.get(n)! })),
        },
      },
    });
    channelCount++;
  }
  console.log(`✓ Channels: ${channelCount} 条`);
}

main().finally(() => prisma.$disconnect());
